// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF0C72GnNXypBHdL7Yn9sXCSJ9uDSYm-Y',
    appId: '1:1015427928595:web:abe9aea1272d51c2b925e6',
    messagingSenderId: '1015427928595',
    projectId: 'remind-81053',
    authDomain: 'remind-81053.firebaseapp.com',
    storageBucket: 'remind-81053.firebasestorage.app',
    measurementId: 'G-H5Z5H1RB9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUhgtgg5HuijfQ37pgj9U6io_yuqjeRus',
    appId: '1:1015427928595:android:7415e6eb1410db92b925e6',
    messagingSenderId: '1015427928595',
    projectId: 'remind-81053',
    storageBucket: 'remind-81053.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-hQ2mHnKVSNuqeH8zDGbMi_KmqYGa3lw',
    appId: '1:1015427928595:ios:698abe509b211bcfb925e6',
    messagingSenderId: '1015427928595',
    projectId: 'remind-81053',
    storageBucket: 'remind-81053.firebasestorage.app',
    iosBundleId: 'com.example.calendario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-hQ2mHnKVSNuqeH8zDGbMi_KmqYGa3lw',
    appId: '1:1015427928595:ios:698abe509b211bcfb925e6',
    messagingSenderId: '1015427928595',
    projectId: 'remind-81053',
    storageBucket: 'remind-81053.firebasestorage.app',
    iosBundleId: 'com.example.calendario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF0C72GnNXypBHdL7Yn9sXCSJ9uDSYm-Y',
    appId: '1:1015427928595:web:2e030506e22a2434b925e6',
    messagingSenderId: '1015427928595',
    projectId: 'remind-81053',
    authDomain: 'remind-81053.firebaseapp.com',
    storageBucket: 'remind-81053.firebasestorage.app',
    measurementId: 'G-506700K4LG',
  );
}
